version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    networks:
      - default
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - ${MONGO_DB_ADMIN_PORT}:${MONGO_DB_ADMIN_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_DB_ADMIN_URL}
    networks:
      - default
  node-server:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - ${NODE_SERVER_PORT}:${NODE_SERVER_PORT}
    networks:
      - default

networks:
  default:
    driver: bridge
